#!/usr/bin/env python3
"""Render spin TOML specs into the profile registry consumed by build scripts."""

from __future__ import annotations

import argparse
import csv
import shlex
import sys
import tomllib
from pathlib import Path
from typing import Any


ROOT = Path.cwd()
SPINS_DIR = ROOT / "configs" / "spins"
REGISTRY = ROOT / "configs" / "profiles.tsv"
VALID_FAMILIES = {"debian", "ubuntu"}
VALID_KINDS = {"live", "autoinstall"}


class SpinError(ValueError):
    pass


def require_table(data: dict[str, Any], name: str, source: Path) -> dict[str, Any]:
    value = data.get(name)
    if not isinstance(value, dict):
        raise SpinError(f"{source}: missing [{name}] table")
    return value


def require_str(table: dict[str, Any], key: str, source: Path) -> str:
    value = table.get(key)
    if not isinstance(value, str) or not value:
        raise SpinError(f"{source}: missing string field {key!r}")
    return value


def optional_str(table: dict[str, Any], key: str) -> str | None:
    value = table.get(key)
    if value is None:
        return None
    if not isinstance(value, str):
        raise SpinError(f"field {key!r} must be a string")
    return value


def optional_scalar(table: dict[str, Any], key: str) -> str | None:
    value = table.get(key)
    if value is None:
        return None
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int | str):
        return str(value)
    raise SpinError(f"field {key!r} must be a string, integer, or boolean")


def shell_value(value: str) -> str:
    return shlex.quote(value)


def env_line(key: str, value: str | None) -> str | None:
    if value is None:
        return None
    return f"{key}={shell_value(value)}"


def load_spin(path: Path) -> dict[str, Any]:
    with path.open("rb") as handle:
        data = tomllib.load(handle)

    spin = require_table(data, "spin", path)
    image = require_table(data, "image", path)
    packages = require_table(data, "packages", path)

    spin_id = require_str(spin, "id", path)
    family = require_str(spin, "family", path)
    kind = require_str(spin, "kind", path)
    profile_dir = require_str(spin, "profile_dir", path)
    description = require_str(spin, "description", path)

    if family not in VALID_FAMILIES:
        raise SpinError(f"{path}: unsupported family {family!r}")
    if kind not in VALID_KINDS:
        raise SpinError(f"{path}: unsupported kind {kind!r}")
    if path.stem != spin_id:
        raise SpinError(f"{path}: filename stem must match spin.id {spin_id!r}")

    metapackages = packages.get("metapackages")
    if not isinstance(metapackages, list) or not metapackages or not all(
        isinstance(item, str) and item for item in metapackages
    ):
        raise SpinError(f"{path}: [packages].metapackages must be a non-empty string array")

    return {
        "path": path,
        "id": spin_id,
        "order": int(spin.get("order", 1000)),
        "family": family,
        "kind": kind,
        "profile_dir": profile_dir,
        "description": description,
        "image": image,
        "debian": data.get("debian", {}),
        "ubuntu": data.get("ubuntu", {}),
        "boot": data.get("boot", {}),
        "desktop": data.get("desktop", {}),
        "artifacts": data.get("artifacts", {}),
        "install": data.get("install", {}),
        "metapackages": metapackages,
    }


def validate_spin(spin: dict[str, Any]) -> None:
    source = spin["path"]
    image = spin["image"]
    require_str(image, "distro_name", source)
    require_str(image, "image_name", source)

    if spin["family"] == "debian":
        debian = spin["debian"]
        if not isinstance(debian, dict):
            raise SpinError(f"{source}: [debian] must be a table")
        for key in ("release", "archive_areas", "mirror_bootstrap", "mirror_chroot_security"):
            require_str(debian, key, source)

    if spin["family"] == "ubuntu":
        ubuntu = spin["ubuntu"]
        if not isinstance(ubuntu, dict):
            raise SpinError(f"{source}: [ubuntu] must be a table")
        require_str(ubuntu, "base_alias", source)
        require_str(ubuntu, "base_iso", source)

    if spin["kind"] == "autoinstall":
        install = spin["install"]
        if not isinstance(install, dict):
            raise SpinError(f"{source}: [install] must be a table")
        for key in ("disk", "timeout", "complete_marker", "boot_timeout", "boot_serial_log"):
            if key not in install:
                raise SpinError(f"{source}: missing [install].{key}")


def profile_env(spin: dict[str, Any]) -> str:
    image = spin["image"]
    debian = spin["debian"]
    ubuntu = spin["ubuntu"]
    boot = spin["boot"]
    desktop = spin["desktop"]
    artifacts = spin["artifacts"]
    install = spin["install"]

    lines: list[str] = [
        "# Generated by scripts/common/render-spins.py; edit configs/spins/*.toml.",
        env_line("DISTRO_NAME", require_str(image, "distro_name", spin["path"])),
        env_line("IMAGE_NAME", require_str(image, "image_name", spin["path"])),
        env_line("ARCHITECTURE", optional_str(image, "architecture")),
        env_line("VOLUME_ID", optional_str(image, "volume_id")),
        env_line("DEBIAN_RELEASE", optional_str(debian, "release")),
        env_line("ARCHIVE_AREAS", optional_str(debian, "archive_areas")),
        env_line("MIRROR_BOOTSTRAP", optional_str(debian, "mirror_bootstrap")),
        env_line("MIRROR_CHROOT_SECURITY", optional_str(debian, "mirror_chroot_security")),
        env_line("BOOTAPPEND_LIVE", optional_str(debian, "bootappend_live")),
        env_line("BOOT_TIMEOUT_TENTHS", optional_scalar(debian, "boot_timeout_tenths")),
        env_line("SERIAL_CONSOLE", optional_scalar(debian, "serial_console")),
        env_line("UBUNTU_BASE_ALIAS", optional_str(ubuntu, "base_alias")),
        env_line("UBUNTU_BASE_ISO", optional_str(ubuntu, "base_iso")),
        env_line("BOOT_MARKER", optional_str(boot, "marker")),
        env_line("BOOT_TEST_TIMEOUT", optional_scalar(boot, "timeout")),
        env_line("BOOT_TEST_MEMORY", optional_scalar(boot, "memory")),
        env_line("DESKTOP_SESSION", optional_str(desktop, "session")),
        env_line("DESKTOP_PANEL_PROCESS", optional_str(desktop, "panel_process")),
        env_line("DESKTOP_DESKTOP_PROCESS", optional_str(desktop, "desktop_process")),
        env_line("DESKTOP_THEME_APPLY", optional_str(desktop, "theme_apply")),
        env_line("SCREENSHOT", optional_str(artifacts, "screenshot")),
        env_line("SERIAL_LOG", optional_str(artifacts, "serial_log")),
        env_line("INSTALL_DISK", optional_str(install, "disk")),
        env_line("INSTALL_CPUS", optional_scalar(install, "cpus")),
        env_line("INSTALL_TEST_TIMEOUT", optional_scalar(install, "timeout")),
        env_line("INSTALL_COMPLETE_MARKER", optional_str(install, "complete_marker")),
        env_line("INSTALL_BOOT_TEST_TIMEOUT", optional_scalar(install, "boot_timeout")),
        env_line("INSTALL_BOOT_SERIAL_LOG", optional_str(install, "boot_serial_log")),
        env_line("CUSTOM_METAPACKAGES", " ".join(spin["metapackages"])),
    ]
    return "\n".join(line for line in lines if line is not None) + "\n"


def render(spins: list[dict[str, Any]]) -> None:
    REGISTRY.parent.mkdir(parents=True, exist_ok=True)
    with REGISTRY.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.writer(handle, delimiter="\t", lineterminator="\n")
        writer.writerow(["id", "family", "kind", "profile_dir", "description"])
        for spin in spins:
            writer.writerow(
                [spin["id"], spin["family"], spin["kind"], spin["profile_dir"], spin["description"]]
            )

    for spin in spins:
        profile_dir = ROOT / spin["profile_dir"]
        profile_dir.mkdir(parents=True, exist_ok=True)
        (profile_dir / "profile.env").write_text(profile_env(spin), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="validate specs without writing outputs")
    args = parser.parse_args()

    paths = sorted(SPINS_DIR.glob("*.toml"))
    if not paths:
        print(f"no spin specs found in {SPINS_DIR}", file=sys.stderr)
        return 1

    try:
        spins = sorted((load_spin(path) for path in paths), key=lambda item: (item["order"], item["id"]))
        seen: set[str] = set()
        for spin in spins:
            if spin["id"] in seen:
                raise SpinError(f"duplicate spin id: {spin['id']}")
            seen.add(spin["id"])
            validate_spin(spin)
    except (OSError, tomllib.TOMLDecodeError, SpinError) as exc:
        print(exc, file=sys.stderr)
        return 1

    if not args.check:
        render(spins)

    for spin in spins:
        print(f"{spin['id']}\t{spin['family']}\t{spin['kind']}\t{spin['profile_dir']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
