[greeter]
background=/usr/share/backgrounds/demuntu/demuntu-default.png
theme-name=DemChrome-Dark
icon-theme-name=DemChrome
font-name=Sans 11
xft-antialias=true
xft-dpi=96
xft-hintstyle=slight
xft-rgba=rgb
indicators=~host;~spacer;~session;~language;~a11y;~clock;~power;
clock-format=%H:%M
